version: '3.7'

services:
  yarn:
    hostname: yarn-temp
    container_name: yarn-temp
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /project/node_modules
      - ./:/project/
    # ports:
    #   - "127.0.0.1:3000:3000"
    restart: always